version: "3"

services:


    frontend:
      build: ./frontend
      links:
        - microusers
        - microproducts
        - microorders 
      ports:
        - "5001:5001"
      networks:
        - clase

    microusers:
      build: ./microUsers
      links:
        - db
      depends_on:
        - db
      ports:
        - "5002:5002"
      networks:
        - clase
      environment:
        MYSQL_HOST: db
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DB: myflaskapp

    microproducts:
      build: ./microProducts
      links:
        - db
      depends_on:
        - db
      ports:
        - "5003:5003"
      networks:
        - clase
      environment:
        MYSQL_HOST: db
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DB: myflaskapp

    microorders:
      build: ./microOrders
      links:
        - db
      depends_on:
        - db
      ports:
        - "5004:5004"
      networks:
        - clase
      environment:
        MYSQL_HOST: db
        MYSQL_USER: root
        MYSQL_PASSWORD: root
        MYSQL_DB: myflaskapp



    db:
      image: "mysql:5.7"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: myflaskapp
      volumes:
        - ./db:/docker-entrypoint-initdb.d/:ro
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - "32000:3306"
      networks:
        - clase

networks:
  clase:
